// <auto-generated />
using System;
using Api.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20220721010915_uf_minicipio_cep")]
    partial class uf_minicipio_cep
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Api.Domain.Entities.CepEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(60) CHARACTER SET utf8mb4")
                        .HasMaxLength(60);

                    b.Property<Guid>("MunicipioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NumeroLogradouro")
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Cep");

                    b.HasIndex("MunicipioId");

                    b.ToTable("CepTable");
                });

            modelBuilder.Entity("Api.Domain.Entities.MunicipioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CodigoIBGE")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeMunicipio")
                        .IsRequired()
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.Property<Guid>("UFId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIBGE");

                    b.HasIndex("UFId");

                    b.ToTable("MunicipioTable");
                });

            modelBuilder.Entity("Api.Domain.Entities.UFEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeUF")
                        .IsRequired()
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.Property<string>("SiglaUF")
                        .IsRequired()
                        .HasColumnType("varchar(2) CHARACTER SET utf8mb4")
                        .HasMaxLength(2);

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SiglaUF")
                        .IsUnique();

                    b.ToTable("UFTable");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22ffbd18-cdb9-45cc-97b0-51e97700bf71"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(5401),
                            NomeUF = "Acre",
                            SiglaUF = "AC"
                        },
                        new
                        {
                            Id = new Guid("7cc33300-586e-4be8-9a4d-bd9f01ee9ad8"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6194),
                            NomeUF = "Alagoas",
                            SiglaUF = "AL"
                        },
                        new
                        {
                            Id = new Guid("cb9e6888-2094-45ee-bc44-37ced33c693a"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6207),
                            NomeUF = "Amazonas",
                            SiglaUF = "AM"
                        },
                        new
                        {
                            Id = new Guid("409b9043-88a4-4e86-9cca-ca1fb0d0d35b"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6210),
                            NomeUF = "Amapá",
                            SiglaUF = "AP"
                        },
                        new
                        {
                            Id = new Guid("5abca453-d035-4766-a81b-9f73d683a54b"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6212),
                            NomeUF = "Bahia",
                            SiglaUF = "BA"
                        },
                        new
                        {
                            Id = new Guid("5ff1b59e-11e7-414d-827e-609dc5f7e333"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6214),
                            NomeUF = "Ceará",
                            SiglaUF = "CE"
                        },
                        new
                        {
                            Id = new Guid("bd08208b-bfca-47a4-9cd0-37e4e1fa5006"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6216),
                            NomeUF = "Distrito Federal",
                            SiglaUF = "DF"
                        },
                        new
                        {
                            Id = new Guid("c623f804-37d8-4a19-92c1-67fd162862e6"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6218),
                            NomeUF = "Espírito Santo",
                            SiglaUF = "ES"
                        },
                        new
                        {
                            Id = new Guid("837a64d3-c649-4172-a4e0-2b20d3c85224"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6220),
                            NomeUF = "Goiás",
                            SiglaUF = "GO"
                        },
                        new
                        {
                            Id = new Guid("57a9e9f7-9aea-40fe-a783-65d4feb59fa8"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6222),
                            NomeUF = "Maranhão",
                            SiglaUF = "MA"
                        },
                        new
                        {
                            Id = new Guid("27f7a92b-1979-4e1c-be9d-cd3bb73552a8"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6224),
                            NomeUF = "Minas Gerais",
                            SiglaUF = "MG"
                        },
                        new
                        {
                            Id = new Guid("3739969c-fd8a-4411-9faa-3f718ca85e70"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6227),
                            NomeUF = "Mato Grosso do Sul",
                            SiglaUF = "MS"
                        },
                        new
                        {
                            Id = new Guid("29eec4d3-b061-427d-894f-7f0fecc7f65f"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6228),
                            NomeUF = "Mato Grosso",
                            SiglaUF = "MT"
                        },
                        new
                        {
                            Id = new Guid("8411e9bc-d3b2-4a9b-9d15-78633d64fc7c"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6230),
                            NomeUF = "Pará",
                            SiglaUF = "PA"
                        },
                        new
                        {
                            Id = new Guid("1109ab04-a3a5-476e-bdce-6c3e2c2badee"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6232),
                            NomeUF = "Paraíba",
                            SiglaUF = "PB"
                        },
                        new
                        {
                            Id = new Guid("ad5969bd-82dc-4e23-ace2-d8495935dd2e"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6234),
                            NomeUF = "Pernambuco",
                            SiglaUF = "PE"
                        },
                        new
                        {
                            Id = new Guid("f85a6cd0-2237-46b1-a103-d3494ab27774"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6236),
                            NomeUF = "Piauí",
                            SiglaUF = "PI"
                        },
                        new
                        {
                            Id = new Guid("1dd25850-6270-48f8-8b77-2f0f079480ab"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6238),
                            NomeUF = "Paraná",
                            SiglaUF = "PR"
                        },
                        new
                        {
                            Id = new Guid("43a0f783-a042-4c46-8688-5dd4489d2ec7"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6241),
                            NomeUF = "Rio de Janeiro",
                            SiglaUF = "RJ"
                        },
                        new
                        {
                            Id = new Guid("542668d1-50ba-4fca-bbc3-4b27af108ea3"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6243),
                            NomeUF = "Rio Grande do Norte",
                            SiglaUF = "RN"
                        },
                        new
                        {
                            Id = new Guid("924e7250-7d39-4e8b-86bf-a8578cbf4002"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6244),
                            NomeUF = "Rondônia",
                            SiglaUF = "RO"
                        },
                        new
                        {
                            Id = new Guid("9fd3c97a-dc68-4af5-bc65-694cca0f2869"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6246),
                            NomeUF = "Roraima",
                            SiglaUF = "RR"
                        },
                        new
                        {
                            Id = new Guid("88970a32-3a2a-4a95-8a18-2087b65f59d1"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6248),
                            NomeUF = "Rio Grande do Sul",
                            SiglaUF = "RS"
                        },
                        new
                        {
                            Id = new Guid("b81f95e0-f226-4afd-9763-290001637ed4"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6250),
                            NomeUF = "Santa Catarina",
                            SiglaUF = "SC"
                        },
                        new
                        {
                            Id = new Guid("fe8ca516-034f-4249-bc5a-31c85ef220ea"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6253),
                            NomeUF = "Sergipe",
                            SiglaUF = "SE"
                        },
                        new
                        {
                            Id = new Guid("e7e416de-477c-4fa3-a541-b5af5f35ccf6"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6255),
                            NomeUF = "São Paulo",
                            SiglaUF = "SP"
                        },
                        new
                        {
                            Id = new Guid("971dcb34-86ea-4f92-989d-064f749e23c9"),
                            CreateAt = new DateTime(2022, 7, 21, 1, 9, 14, 772, DateTimeKind.Utc).AddTicks(6257),
                            NomeUF = "Tocantins",
                            SiglaUF = "TO"
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(60) CHARACTER SET utf8mb4")
                        .HasMaxLength(60);

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("user");
                });

            modelBuilder.Entity("Api.Domain.Entities.CepEntity", b =>
                {
                    b.HasOne("Api.Domain.Entities.MunicipioEntity", "Municipio")
                        .WithMany("Ceps")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Domain.Entities.MunicipioEntity", b =>
                {
                    b.HasOne("Api.Domain.Entities.UFEntity", "UF")
                        .WithMany("Municipios")
                        .HasForeignKey("UFId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
